stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm i
    - npm run build

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master